spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3315/test_db?useSSL=false
    username: root
    password: secret
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
